services:
  frontend:
    image: kikimora22/ascii-front:latest
    container_name: ascii-front
    restart: always
    ports:
      - "8000:80"
  
  backend:
    image: kikimora22/ascii-back:latest
    container_name: ascii-backend
    restart: always
    ports:
      - "8080:8080"
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/app.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt # Тут будуть лежати сертифікати
      - ./certbot/www:/var/www/certbot  # Це папка для ACME challenge
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot