# HTTP → HTTPS редірект
server {
    listen 80;
    server_name ascii-art.space www.ascii-art.space;

    return 301 https://$host$request_uri;
}

# HTTPS сервер
server {
    listen 443 ssl;
    server_name ascii-art.space www.ascii-art.space;

    ssl_certificate /etc/letsencrypt/live/ascii-art.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ascii-art.space/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}