name: Infrastructure CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy changes to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /opt/ASCII-Infra

            git pull origin main

            docker run --rm -t -v $(pwd)/nginx_config_path:/etc/nginx/nginx.conf:ro nginx:alpine nginx -t

            docker compose up -d --build

            sleep 5
            if [ "$(docker inspect -f '{{.State.Running}}' nginx)" != "true" ]; then
              echo "Nginx failed to start!"
              docker compose logs nginx
              exit 1
            fi

            docker image prune -f