name: Infrastructure CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy changes to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /opt/ASCII-Infra
            
            git pull origin main
            
            # 1. Перевіряємо конфіг за допомогою тимчасового контейнера
            # Це безпечно: якщо в конфігу помилка, пайплайн зупиниться тут
            docker compose run --rm nginx nginx -t
            
            # 2. Піднімаємо або оновлюємо сервіси
            docker compose up -d
            
            # 3. На всякий випадок кажемо nginx перечитати конфіги (хоча up -d має це зробити)
            docker compose exec -T nginx nginx -s reload